branch-defaults:
  master:
    environment: master-docker-circleci-test
  staging:
    environment: staging-docker-circleci-test
global:
  application_name: docker_circleci_test
  branch: null
  default_ec2_keyname: null
  default_platform: Docker 18.06.1-ce
  default_region: eu-west-2
  # profile: eb-cli
  sc: git
  workspace_type: Application
