branch-defaults:
  master:
    environment: master-docker-circleci-test
global:
  application_name: docker_circleci_test
  default_platform: Docker 18.06.1-ce
  default_region: eu-west-2
  sc: git
  workspace_type: Application
