version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Building Images
          command: |
            docker-compose up -d
            ls -l
      - run:
          name: Testing Images
          command: |
            docker container ls -a
            docker exec -it app_server_1
            ls -a
