version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Building Images
          command: |
            docker-compose up -d
            docker container ls -a
      - run:
          name: Testing Images
          command: |
            docker exec -it project_server_1 sh
            ls
            npm run test
