version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: |
            apt-get update
            apt-get install awsebcli --upgrade
      - run:
          name: Building Images
          command: |
            docker-compose up -d
            docker container ls -a
      - run:
          name: Testing Images
          command: |
            docker exec -it project_server_1 npm run test
      - run:
          name: Deploying Images
          command: |
            eb deploy $CIRCLE_BRANCH-circleci-test
