version: 2
jobs:
  build:
    docker:
      - image: node:10.15.1
    steps:
      - checkout
      - run:
          name: install & build
          command: |
            npm i
            npm run test
