version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Building Images
          command: |
            docker-compose up -d
      - run:
          name: Testing Images
          command: |
            docker exec -it app_server_1 sh
            ls
            npm run test
