version: 2
jobs:
  build:
    docker:
      - image: node:10.15.1
    steps:
      - checkout
      - run:
          name: install
          command: npm i
      - run:
          name: test
          command: npm run test
